version: '3.8'

services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nice_team
      POSTGRES_PASSWORD: cfz{O3(F9me#TXj
      POSTGRES_DB: football_league
    volumes:
      - pg_db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    network_mode: host

volumes:
  pg_db: